/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Unit6.OOP.Class;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author CHINDA
 */
public class ExDictionary extends javax.swing.JFrame {

  /**
   * Creates new form ExDictionary
   */
  public ExDictionary() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    sp = new javax.swing.JScrollPane();
    list = new javax.swing.JList<>();
    jPanel1 = new javax.swing.JPanel();
    txtSearch = new javax.swing.JTextField();
    jScrollPane2 = new javax.swing.JScrollPane();
    txtResult = new javax.swing.JTextPane();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });

    list.setFont(new java.awt.Font("Kh Content", 0, 14)); // NOI18N
    list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        listValueChanged(evt);
      }
    });
    sp.setViewportView(list);

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 0, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 36, Short.MAX_VALUE)
    );

    txtSearch.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
    txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyTyped(java.awt.event.KeyEvent evt) {
        txtSearchKeyTyped(evt);
      }
    });

    txtResult.setContentType("text/html"); // NOI18N
    txtResult.setFont(new java.awt.Font("Kh Content", 0, 14)); // NOI18N
    txtResult.setFocusable(false);
    jScrollPane2.setViewportView(txtResult);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(sp, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
          .addComponent(txtSearch))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jScrollPane2)
          .addComponent(sp, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents
  private DefaultListModel<String> mod;
  private ArrayList<ClsDictionary> ls; 
  private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    mod = new DefaultListModel<>();
    ls = new ArrayList<>();
    list.setModel(mod);
    ClsDictionary dic;
    dic = new ClsDictionary("apple", "apple <font color = red>(n)</font>: ផ្លែប៉ោម");
    ls.add(dic);
    mod.addElement(dic.getWord());
    
    dic = new ClsDictionary("boy", "boy <font color = red>(n)</font>: ក្មេងប្រុស");
    ls.add(dic);
    mod.addElement(dic.getWord());
   
    
  }//GEN-LAST:event_formWindowOpened

  private void listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listValueChanged
    if(!list.isSelectionEmpty()){
      int index = list.getSelectedIndex();
      ClsDictionary dic = ls.get(index);
      txtResult.setText(dic.getDecription());
    }
  }//GEN-LAST:event_listValueChanged

  private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
    String text = txtSearch.getText().trim();
    text+=evt.getKeyChar();
    text=text.toLowerCase().trim();
    for(int i=0; i<mod.size(); i++){
      String val = ""+mod.getElementAt(i);
      val = val.toLowerCase().trim();
      if(val.startsWith(text)){
        list.setSelectedIndex(i);
        return;
      }
    }
    txtResult.setText("Not found");
    list.clearSelection();
  }//GEN-LAST:event_txtSearchKeyTyped

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ExDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ExDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ExDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ExDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new ExDictionary().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JList<String> list;
  private javax.swing.JScrollPane sp;
  private javax.swing.JTextPane txtResult;
  private javax.swing.JTextField txtSearch;
  // End of variables declaration//GEN-END:variables
}
